[package]
name = "message_length"
version = "0.1.0"
authors = ["Zack M. Davis <code@zackmdavis.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
